### ISSUE TITLE
Le lien sur la presentation semble ne pas marcher

### ISSUE THREAD

**Issue by acopinot** [DirtyF/compte-rendu-pun#5]
@DirtyF : je ne suis pas sure, mais il semble que le lien sur la présentation avec nos noms ne marche pas.

**Comment by DirtyF** [comment]
J'en ai fait un lien Jekyll, il marche depuis https://dirtyf.github.io/compte-rendu-pun/ (par contre dans le markdown en effet ça doit pas passer)

**Comment by DirtyF** [comment]
Le lien a été inséré directement en HTML pour que le lien marche aussi dans le Markdown
